Implementacao/lab/core/urls.py
from django.contrib import admin
from django.urls import path, include
from coin_system import views
from coin_system.view_classes import aluno, empresa, professor, vantagem

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),
    path('', include('django.contrib.auth.urls')),
    path('minhas-moedas', views.my_coins, name='minhas-moedas'),
    path('trocar-moedas', views.exchange_coins, name='trocar-moedas'),
    path('cadastrar-vantagem', views.empresa_create_vantagem, name='cadastrar-vantagem'),
    path('minhas-vantagens', views.empresa_minhas_vantagens, name='minhas-vantagens'),
    path('cadastro/<slug:registration_type>', views.cadastro, name='cadastro'),

    path('alunos', aluno.AlunoListView.as_view(), name='aluno-list'),
    path('aluno/novo', aluno.AlunoCreateView.as_view(), name='aluno-new'),
    path('aluno/<int:pk>', aluno.AlunoDetailView.as_view(), name='aluno-details'),
    path('aluno/editar/<int:pk>', aluno.AlunoUpdateView.as_view(), name='aluno-update'),
    path('aluno/deletar/<int:pk>', aluno.AlunoDeleteView.as_view(), name='aluno-delete'),

    path('empresas', empresa.EmpresaListView.as_view(), name='empresa-list'),
    path('empresa/novo', empresa.EmpresaCreateView.as_view(), name='empresa-new'),
    path('empresa/<int:pk>', empresa.EmpresaDetailView.as_view(), name='empresa-details'),
    path('empresa/editar/<int:pk>', empresa.EmpresaUpdateView.as_view(), name='empresa-update'),
    path('empresa/deletar/<int:pk>', empresa.EmpresaDeleteView.as_view(), name='empresa-delete'),

    path('vantagens', vantagem.VantagemListView.as_view(), name='vantagem-list'),
    path('vantagem/novo', vantagem.VantagemCreateView.as_view(), name='vantagem-new'),
    path('vantagem/<int:pk>', vantagem.VantagemDetailView.as_view(), name='vantagem-details'),
    path('vantagem/editar/<int:pk>', vantagem.VantagemUpdateView.as_view(), name='vantagem-update'),
    path('vantagem/deletar/<int:pk>', vantagem.VantagemDeleteView.as_view(), name='vantagem-delete'),

    path('professores', professor.ProfessorListView.as_view(), name='professor-list'),
    path('professor/novo', professor.ProfessorCreateView.as_view(), name='professor-new'),
    path('professor/<int:pk>', professor.ProfessorDetailView.as_view(), name='professor-details'),
    path('professor/editar/<int:pk>', professor.ProfessorUpdateView.as_view(), name='professor-update'),
    path('professor/deletar/<int:pk>', professor.ProfessorDeleteView.as_view(), name='professor-delete')
]

Implementacao/lab/coin_system/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Aluno(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, blank=True, null=True)
    nome = models.CharField(max_length=120)
    email = models.EmailField()
    cpf = models.CharField(max_length=16)
    rg = models.CharField(max_length=24)
    endereco = models.CharField(max_length=240)
    instituicao_ensino = models.CharField(max_length=80)
    curso = models.CharField(max_length=80)
    saldo = models.IntegerField(default=0)


class Professor(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, blank=True, null=True)
    nome = models.CharField(max_length=120)
    cpf = models.CharField(max_length=16)
    departamento = models.CharField(max_length=80)
    instituicao_ensino = models.CharField(max_length=80)
    saldo = models.IntegerField(default=0)


class Empresa(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, blank=True, null=True)
    nome = models.CharField(max_length=120)

    def __str__(self):
        return self.nome


class Vantagem(models.Model):
    nome = models.CharField(max_length=120)
    descricao = models.TextField()
    foto = models.CharField(max_length=360, default='', blank=True, null=True)
    empresa = models.ForeignKey(Empresa, on_delete=models.CASCADE)
    valor = models.IntegerField(default=0)


class Transacao(models.Model):
    professor = models.ForeignKey(Professor, on_delete=models.CASCADE, null=True, blank=True, default=None)
    aluno = models.ForeignKey(Aluno, on_delete=models.CASCADE)
    vantagem = models.ForeignKey(Vantagem, on_delete=models.CASCADE, null=True, blank=True, default=None)
    valor = models.IntegerField(default=0)
    date = models.DateTimeField(auto_now_add=True)

Implementacao/lab/coin_system/views.py
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
from django.template import loader
from django.shortcuts import render, redirect
from .models import Vantagem
from .utils import get_coin_transfer_context, process_coin_exchange, process_coin_transfer, register_user, create_empresa_vantagem

def home(request):
    return render(request, 'home.html')

@login_required(login_url='/login')
def my_coins(request):
    template = loader.get_template('minhas-moedas.html')
    updated = False

    if request.method == 'POST':
        process_coin_transfer(request.user, request.POST.copy())
        updated = True

    context = get_coin_transfer_context(request.user, updated)
    if context is None:
        return redirect('/')
    return HttpResponse(template.render(context, request))


@login_required(login_url='/login')
def exchange_coins(request):
    template = loader.get_template('exchange-coins.html')

    if request.method == 'POST':
        template = loader.get_template('exchange-success.html')
        context = process_coin_exchange(request.user, request.POST.copy())
    else:
        context = get_coin_transfer_context(request.user, False)

    return HttpResponse(template.render(context, request))


@login_required(login_url='/login')
def empresa_create_vantagem(request):
    template = loader.get_template('empresa-create-vantagem.html')

    if request.method == 'POST' and request.user.empresa:
        context = create_empresa_vantagem(request.POST.copy(), request.user.empresa)
    else:
        context = {
            'none': None
        }

    return HttpResponse(template.render(context, request))


@login_required(login_url='/login')
def empresa_minhas_vantagens(request):
    template = loader.get_template('vantagem/list.html')

    if request.user.empresa:
        context = {
            'vantagens': Vantagem.objects.filter(empresa=request.user.empresa).order_by('nome')
        }
    else:
        return redirect('/')

    return HttpResponse(template.render(context, request))


def cadastro(request, registration_type):
    template = loader.get_template('cadastro.html')

    if registration_type != 'aluno' and registration_type != 'empresa':
        return redirect('/')

    if request.method == 'POST':
        context = register_user(request.POST.copy(), registration_type)
    else:
        context = {'is_aluno': registration_type == 'aluno'}

    return HttpResponse(template.render(context, request))

Implementacao/lab/coin_system/templates/aluno/create.html
{% extends "base.html" %}

{% block container %}
<div class="card">
    <div class="card-header">
        <h5 class="card-title">Cadastrar novo Aluno</h5>
    </div>
    <div class="card-body">
        <form method="post">
            {% csrf_token %}
            {{form.as_p}}
            <button type="submit" class="btn btn-success">Salvar</button>
        </form>
    </div>
</div>
{% endblock %}

Implementacao/lab/coin_system/templates/aluno/delete.html
{% extends "base.html" %}
{% block container %}
<div class="card">
    <div class="card-header">
        <h5 class="card-title">Deletar Aluno #{{object.id}}</h5>
    </div>
    <div class="card-body">
        <form method="post">
            {% csrf_token %}
            <div class="alert alert-warning" role="alert">
                Você tem certeza de que quer deletar <strong>{{ object.nome }}</strong>?
            </div>
            <button type="submit" class="btn btn-danger">Deletar</button>
        </form>
    </div>
</div>
{% endblock %}

Implementacao/lab/coin_system/templates/aluno/detail.html
{% extends "base.html" %}
{% block container %}

<div class="card">
    <div class="card-header">
        <h5 class="card-title">Detalhes do Aluno #{{aluno.id}}</h5>
    </div>
    <div class="card-body">
    <dl class="row">
      <dt class="col-sm-3">Nome</dt>
      <dd class="col-sm-9">{{ aluno.nome }}</dd>
      <dt class="col-sm-3">E-mail</dt>
      <dd class="col-sm-9">{{ aluno.email }}</dd>
      <dt class="col-sm-3">CPF</dt>
      <dd class="col-sm-9">{{ aluno.cpf }}</dd>
      <dt class="col-sm-3">RG</dt>
      <dd class="col-sm-9">{{ aluno.rg }}</dd>
      <dt class="col-sm-3">Endereço</dt>
      <dd class="col-sm-9">{{ aluno.endereco }}</dd>
      <dt class="col-sm-3">Instituição de ensino</dt>
      <dd class="col-sm-9">{{ aluno.instituicao_ensino }}</dd>
      <dt class="col-sm-3">Curso</dt>
      <dd class="col-sm-9">{{ aluno.curso }}</dd>
      <dt class="col-sm-3">Saldo (moedas)</dt>
      <dd class="col-sm-9">{{ aluno.saldo }}</dd>
    </dl>

    </div>
</div>

{% endblock %}

Implementacao/lab/coin_system/templates/aluno/list.html
{% extends "base.html" %}

{% block container %}
<a href="{% url 'aluno-new' %}" class="btn btn-success mb-5">Criar novo</a>
<table class="table">
    <tr>
        <thead class="thead-light">
            <tr>
                <th scope="col">Nome</th>
                <th scope="col">E-mail</th>
                <th scope="col">Saldo</th>
                <th scope="col">Editar</th>
            </tr>
        </thead>
        <tbody>
            {% for aluno in alunos %}
            <tr>
                <td>{{aluno.nome}}</td>
                <td>{{aluno.email}}</td>
                <td>{{aluno.saldo}}</td>
                <td class="d-flex flex-row justify-content-between">
                    <a href="{% url 'aluno-details' aluno.pk %}">Detalhes</a>
                    <a href="{% url 'aluno-update' aluno.pk %}">Editar</a>
                    <a href="{% url 'aluno-delete' aluno.pk %}">Apagar</a>
                </td>
            </tr>
            {% endfor %}
        </tbody>
</table>
{% if is_paginated %}
    {% include "pagination.html" %}
{% endif %}

{% endblock %}

Implementacao/lab/coin_system/templates/aluno/update.html
{% extends "base.html" %}
{% block container %}
<div class="card">
    <div class="card-header">
        <h5 class="card-title">Atualizar Aluno #{{aluno.id}}</h5>
    </div>
    <div class="card-body">
        <form method="post">
            {% csrf_token %}
            {{form.as_p}}
            <button type="submit" class="btn btn-success">Atualizar</button>
        </form>
    </div>
</div>
{% endblock %}

Implementacao/lab/coin_system/templates/base.html
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  {% block meta_tags %}{% endblock %}
  <title>{% block title %}Sistema de gestão de alunos{% endblock %}</title>

  {% block css %}
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  {% endblock %}

  {% block custom_css %}
  {% endblock %}
</head>
<body>

  {% block navbar %}
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container">
      <a class="navbar-brand" href="#">Sistema</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          {% if request.user.is_authenticated %}
            {% if request.user.is_superuser %}
              <li class="nav-item active">
                <a class="nav-link" href="{% url 'empresa-list' %}">Empresas</a>
              </li>
              <li class="nav-item active">
                <a class="nav-link" href="{% url 'aluno-list' %}">Alunos</a>
              </li>
              <li class="nav-item active">
                <a class="nav-link" href="{% url 'professor-list' %}">Professores</a>
              </li>
              <li class="nav-item active">
                <a class="nav-link" href="{% url 'vantagem-list' %}">Vantagens</a>
              </li>
            {% endif %}
            {% if request.user.professor or request.user.aluno %}
              <li class="nav-item active">
                <a class="nav-link" href="{% url 'minhas-moedas' %}">Minhas moedas</a>
              </li>
            {% endif %}
            {% if request.user.aluno %}
              <li class="nav-item active">
                <a class="nav-link" href="{% url 'trocar-moedas' %}">Trocar moedas</a>
              </li>
              <li class="nav-item active">
                <a class="nav-link" href="{% url 'vantagem-list' %}">Vantagens</a>
              </li>
            {% endif %}
            {% if request.user.empresa %}
              <li class="nav-item active">
                <a class="nav-link" href="{% url 'cadastrar-vantagem' %}">Cadastrar vantagem</a>
              </li>
              <li class="nav-item active">
                <a class="nav-link" href="{% url 'minhas-vantagens' %}">Minhas vantagens</a>
              </li>
            {% endif %}
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'logout' %}">Logout</a>
            </li>
          {% else %}
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'login' %}">Login</a>
            </li>
          {% endif %}
        </ul>
      </div>
    </div>
  </nav>
  {% endblock %}

  <div class="container mt-4">
  {% block container %}
  {% endblock %}
  </div>

  {% block js %}
  <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
  {% endblock %}

  {% block custom_js %}
  {% endblock %}
</body>
</html>

Implementacao/lab/coin_system/templates/cadastro.html
{% extends "base.html" %}

{% block container %}
  <div class="card">
    <div class="card-header">
      Cadastro
    </div>
    <div class="card-body">
      {% if error %}
      <div class="alert alert-danger my-3 text-center" role="alert">
        Erro ao criar usuário: {{error}}
      </div>
      {% elif success %}
      <div class="alert alert-success my-3 text-center" role="alert">
        Usuário criado com sucesso. <a href="{% url 'login' %}">Ir para login</a>
      </div>
      {% endif %}
      <form action="" method="POST" class="d-flex flex-column">
        {% csrf_token %}
        <input class="form-control my-2" type="text" name="user" placeholder="Nome de usuário" required>
        <input class="form-control my-2" type="password" name="password" placeholder="Senha" required>
        <input class="form-control my-2" type="email" name="email" placeholder="Email" required>
        <input class="form-control mt-2 mb-5" type="text" name="nome" placeholder="Nome" required>

        {% if is_aluno %}
          <input class="form-control my-2" type="text" name="cpf" placeholder="CPF" required>
          <input class="form-control my-2" type="text" name="rg" placeholder="RG" required>
          <input class="form-control my-2" type="text" name="endereco" placeholder="Endereço" required>
          <input class="form-control my-2" type="text" name="instituicao" placeholder="Instituição de ensino" required>
          <input class="form-control my-2" type="text" name="curso" placeholder="Curso" required>
        {% endif %}
        <button type="submit" class="button btn btn-success mt-5">Cadastrar</button>
      </form>
    </div>
  </div>
{% endblock %}

Implementacao/lab/coin_system/templates/empresa-create-vantagem.html
{% extends "base.html" %}

{% block container %}
  <div class="card">
    <div class="card-header">
      Criar vantagem
    </div>
    <div class="card-body">
      {% if created %}
      <div class="alert alert-success my-3 text-center" role="alert">
        Vantagem cadastrada com sucesso
      </div>
      {% endif %}
      <form action="" method="POST" class="d-flex flex-column">
        {% csrf_token %}
        <input class="form-control my-2" type="text" name="nome" placeholder="Nome" required>
        <textarea class="form-control my-2" name="descricao" rows="4" placeholder="Descrição" required></textarea>
        <input class="form-control my-2" type="number" name="valor" placeholder="Valor" required>

        <button type="submit" class="button btn btn-success mt-5">Cadastrar</button>
      </form>
    </div>
  </div>
{% endblock %}

Implementacao/lab/coin_system/templates/empresa/create.html
{% extends "base.html" %}

{% block container %}
<div class="card">
    <div class="card-header">
        <h5 class="card-title">Cadastrar nova Empresa</h5>
    </div>
    <div class="card-body">
        <form method="post">
            {% csrf_token %}
            {{form.as_p}}
            <button type="submit" class="btn btn-success">Salvar</button>
        </form>
    </div>
</div>
{% endblock %}

Implementacao/lab/coin_system/templates/empresa/delete.html
{% extends "base.html" %}
{% block container %}
<div class="card">
    <div class="card-header">
        <h5 class="card-title">Deletar Empresa #{{object.id}}</h5>
    </div>
    <div class="card-body">
        <form method="post">
            {% csrf_token %}
            <div class="alert alert-warning" role="alert">
                Você tem certeza de que quer deletar <strong>{{ object.nome }}</strong>? Todas as vantagens associadas a ela também serão apagadas
            </div>
            <button type="submit" class="btn btn-danger">Deletar</button>
        </form>
    </div>
</div>
{% endblock %}

Implementacao/lab/coin_system/templates/empresa/detail.html
{% extends "base.html" %}
{% block container %}

<div class="card">
    <div class="card-header">
        <h5 class="card-title">Detalhes da empresa #{{empresa.id}}</h5>
    </div>
    <div class="card-body">
    <dl class="row">
      <dt class="col-sm-3">Nome</dt>
      <dd class="col-sm-9">{{ empresa.nome }}</dd>
    </dl>

    </div>
</div>

{% endblock %}

Implementacao/lab/coin_system/templates/empresa/list.html
{% extends "base.html" %}

{% block container %}
<a href="{% url 'empresa-new' %}" class="btn btn-success mb-5">Criar nova</a>
<table class="table">
    <tr>
        <thead class="thead-light">
            <tr>
                <th scope="col">Nome</th>
                <th scope="col">Editar</th>
            </tr>
        </thead>
        <tbody>
            {% for empresa in empresas %}
            <tr>
                <td>{{empresa.nome}}</td>
                <td class="d-flex flex-row justify-content-between">
                    <a href="{% url 'empresa-details' empresa.pk %}">Detalhes</a>
                    <a href="{% url 'empresa-update' empresa.pk %}">Editar</a>
                    <a href="{% url 'empresa-delete' empresa.pk %}">Apagar</a>
                </td>
            </tr>
            {% endfor %}
        </tbody>
</table>
{% if is_paginated %}
    {% include "pagination.html" %}
{% endif %}

{% endblock %}

Implementacao/lab/coin_system/templates/empresa/update.html
{% extends "base.html" %}
{% block container %}
<div class="card">
    <div class="card-header">
        <h5 class="card-title">Atualizar Empresa #{{empresa.id}}</h5>
    </div>
    <div class="card-body">
        <form method="post">
            {% csrf_token %}
            {{form.as_p}}
            <button type="submit" class="btn btn-success">Atualizar</button>
        </form>
    </div>
</div>
{% endblock %}

Implementacao/lab/coin_system/templates/exchange-coins.html
{% extends "base.html" %}

{% block container %}
  <div class="card">
    <div class="alert alert-primary my-3 text-center" role="alert">
      Meu saldo: <strong>{{ saldo }}</strong> moedas
    </div>

    {% if request.user.aluno %}
      <div>
        <form action="{% url 'trocar-moedas' %}" method="POST" class="d-flex flex-column align-items-center w-100 px-3 mb-3">
          <h3>Trocar moedas</h3>
          {% csrf_token %}
          <div class="w-100 d-flex flex-column align-items-center my-4">
            <label for="vantagem">Vantagem:</label>
            <select name="vantagem" class="form-control" required>
              {% for vantagem in vantagem_list %}
                <option value="{{vantagem.id}}" {% if vantagem.valor > saldo %}disabled{% endif %}>{{vantagem.nome}} - {{vantagem.valor}} moedas</option>
              {% endfor %}
            </select>
          </div>
          <button type="submit" class="btn btn-success">Trocar</button>
        </form>
      </div>
    {% endif %}
  </div>
{% endblock %}

Implementacao/lab/coin_system/templates/exchange-success.html
{% extends "base.html" %}

{% block container %}
  <div class="card">
    <div class="card-body">
      {% if error %}
        <h1>Erro ao processar solicitação</h1>
        <div class="alert alert-danger my-3 text-center" role="alert">
          {{message}}
        </div>
      {% else %}
        <h1>Troca de moedas feita com sucesso!</h1>
        <div class="alert alert-success my-3 text-center" role="alert">
          Número de confirmação: <strong>#{{confirmation}}</strong>
        </div>
      {% endif %}
    </div>
  </div>
{% endblock %}

Implementacao/lab/coin_system/templates/home.html
{% extends "base.html" %}

{% block container %}
  <div class="card">
    <h1>Sistema de moedas</h1>
  </div>
{% endblock %}

Implementacao/lab/coin_system/templates/minhas-moedas.html
{% extends "base.html" %}

{% block container %}
  <div class="card">
    {% if updated %}
      <div class="alert alert-success my-3 text-center" role="alert">
        Transferência realizada com sucesso.
      </div>
    {% endif %}
    <div class="alert alert-primary my-3 text-center" role="alert">
      Meu {% if updated %}novo {% endif %}saldo: <strong>{{ saldo }}</strong> moedas
    </div>

  <table class="table my-4">
    <h3 class="text-center">Transações</h3>
    <thead class="thead-light">
      <tr>
        {% if request.user.professor %}
          <th scope="col">Destinatário/Remetente</th>
        {% endif %}
        {% if request.user.aluno %}
          <th scope="col">Vantagem/Remetente</th>
        {% endif %}
        <th scope="col">Valor</th>
        <th scope="col">Data</th>
      </tr>
    </thead>
    <tbody>
      {% for transacao in transaction_list %}
      <tr>
        {% if request.user.professor and transacao.aluno %}
          <td>{{transacao.aluno.nome}}</td>
        {% elif request.user.professor %}
          <td>Administrador</td>
        {% endif %}

        {% if request.user.aluno and transacao.vantagem %}
          <td>{{transacao.vantagem.nome}}</td>
        {% elif request.user.aluno %}
          <td>Prof. {{transacao.professor.nome}}</td>
        {% endif %}


        {% if request.user.professor and transacao.aluno %}
          <td>-{{transacao.valor}} moedas</td>
        {% elif request.user.professor %}
          <td>+{{transacao.valor}} moedas</td>
        {% endif %}

        {% if request.user.aluno and transacao.vantagem %}
          <td>-{{transacao.valor}} moedas</td>
        {% elif request.user.aluno %}
          <td>+{{transacao.valor}} moedas</td>
        {% endif %}


        <td>{{transacao.date|date:'d/m/Y'}}</td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
    

    {% if request.user.professor %}
      <div>
        <form action="" method="POST" class="d-flex flex-column align-items-center w-100 px-3 mb-3">
          <h3>Transferir moedas</h3>
          {% csrf_token %}
          <div class="w-100 d-flex flex-row">
            <label for="value">Número de moedas para transferir:</label>
            <input type="number" class="form-control my-3" name="value" required min="1" max="{{saldo}}">
          </div>
          <div class="w-100 d-flex flex-row justify-content-start">
            <label for="aluno">Aluno destinatário:</label>
            <select name="aluno" class="form-control" required>
              {% for aluno in aluno_list %}
                <option value="{{aluno.id}}">{{aluno.nome}}</option>
              {% endfor %}
            </select>
          </div>
          <button type="submit" class="btn btn-success">Salvar</button>
        </form>
      </div>
    {% endif %}
  </div>
{% endblock %}

Implementacao/lab/coin_system/templates/pagination.html
<nav aria-label="navigation">
  <ul class="pagination justify-content-end mb-0">
{% if page_obj.has_previous %}
  <li class="page-item">
      <a class="page-link" href="?page={{ page_obj.previous_page_number }}">
          <i class="fas fa-angle-left"></i>
          <span class="sr-only">Anterior</span>
      </a>
  </li>
{% else %}
  <li class="page-item disabled">
      <a class="page-link" href="#">
          <i class="fas fa-angle-left"></i>
          <span class="sr-only">Anterior</span>
      </a>
  </li>
{% endif %}

{% for i in page_obj.paginator.page_range %}
  {% if page_obj.number == i %}
  <li class="page-item active">
      <a class="page-link" href="?page={{ i }}">{{ page_obj.number }}</a>
    </li>
  {% elif i > page_obj.number|add:'-5' and i < page_obj.number|add:'5' %}
  <li class="page-item">
      <a class="page-link" href="?page={{ i }}">{{ i }}</a>
    </li>
  {% endif %}
{% endfor %}

{% if page_obj.paginator.num_pages > page_obj.number|add:'4' %}
  <li><a class="page-link" href="?page={{ page_obj.number|add:'5' }}">&hellip;</a></li>
{% endif %}

{% if page_obj.has_next %}
  <li class="page-item">
      <a class="page-link" href="?page={{ page_obj.next_page_number }}">
        <i class="fas fa-angle-right"></i>
        <span class="sr-only">Próxima</span>
      </a>
    </li>
{% else %}
  <li class="page-item disabled">
      <a class="page-link" href="#">
          <i class="fas fa-angle-right"></i>
          <span class="sr-only">Próxima</span>
      </a>
  </li>
{% endif %}
</ul>
</nav>

Implementacao/lab/coin_system/templates/professor/create.html
{% extends "base.html" %}

{% block container %}
<div class="card">
    <div class="card-header">
        <h5 class="card-title">Cadastrar novo Professor</h5>
    </div>
    <div class="card-body">
        <form method="post">
            {% csrf_token %}
            {{form.as_p}}
            <button type="submit" class="btn btn-success">Salvar</button>
        </form>
    </div>
</div>
{% endblock %}

Implementacao/lab/coin_system/templates/professor/delete.html
{% extends "base.html" %}
{% block container %}
<div class="card">
    <div class="card-header">
        <h5 class="card-title">Deletar Professor #{{object.id}}</h5>
    </div>
    <div class="card-body">
        <form method="post">
            {% csrf_token %}
            <div class="alert alert-warning" role="alert">
                Você tem certeza de que quer deletar <strong>{{ object.nome }}</strong>?
            </div>
            <button type="submit" class="btn btn-danger">Deletar</button>
        </form>
    </div>
</div>
{% endblock %}

Implementacao/lab/coin_system/templates/professor/update.html
{% extends "base.html" %}
{% block container %}
<div class="card">
    <div class="card-header">
        <h5 class="card-title">Atualizar Professor #{{professor.id}}</h5>
    </div>
    <div class="card-body">
        <form method="post">
            {% csrf_token %}
            {{form.as_p}}
            <button type="submit" class="btn btn-success">Atualizar</button>
        </form>
    </div>
</div>
{% endblock %}